apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  # The interval at which to check the upstream for updates
  interval: 30m
  # The repository URL, can be a HTTP/S or SSH address
  url: https://github.com/kubernetes/ingress-nginx
  # The Git reference to checkout and monitor for changes
  # (defaults to master)
  # For all available options, see:
  # https://toolkit.fluxcd.io/components/source/api/#source.toolkit.fluxcd.io/v1.GitRepositoryRef
  ref:
    branch: master
